# Generated by Django 4.2.20 on 2025-04-05 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_formatchoice_genrechoice_video_added_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
