# Generated by Django 4.2.20 on 2025-04-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_video_updated_on_alter_video_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='keyword',
            field=models.JSONField(blank=True, help_text='Relevant tags or keywords that help in searching or categorizing the video'),
        ),
    ]
